language: go
go:
  - 1.x
sudo: true
addons:
  apt:
    packages:
    - iproute
before_install:
  - go get -d ./...
install:
  - go build -v ./...
before_script:
  - sudo ip link add name br-test type bridge
  - sudo ip link set br-test up
  - sudo ip addr add 10.0.42.1/24 dev br-test
